### PR TITLE
Display where an article was cross-posted

### PR DESCRIPTION
**Pull request by akenn**
I thought it would be cool to link to other places where an article was posted. Here's what that looks like:

screen shot 2015-01-20 at 12 29 03 pm

Let me know if there are any articles I missed.

### CODE REVIEW

**Comment by likethemammal** [comment]
Thats fuckin baller

**Comment by likethemammal** [comment]
I'm trying to think of how we can automate this process. I can't really think of anyway to do it at the moment tho.

**Comment by MarcoPolo** [comment]
:baseball: 'er

**Comment by mediocregopher** [comment]
:+1:

**Comment by MarcoPolo** [comment]
Merge it!!11one

**Pull request merged**
